import type { TSchema } from "@sinclair/typebox";
import {
  AccountMetricSchema,
  CatalogRewardDefinitionSchema,
  EarningExclusionsSchema,
  EarningPolicySchema,
  ExpiringBalanceSchema,
  MemberAccountRequestSchema,
  MemberAccountResponseSchema,
  PointExpirationPolicySchema,
  ProgramAccountDefinitionSchema,
  ProgramCatalogSchema,
  ProgramGetRequestSchema,
  ProgramGetResponseSchema,
  ProgramMetricDefinitionSchema,
  TierBenefitSchema,
  TierDefinitionSchema,
  TierQualificationPolicySchema,
  TierProgressSchema
} from "./account.js";
import {
  CapabilitiesDocumentSchema,
  HealthDocumentSchema,
  WellKnownDocumentSchema
} from "./discovery.js";
import { LoyaltyEventSchema } from "./events.js";
import {
  AccrualPostRequestSchema,
  EvaluationRequestSchema,
  EvaluationResponseSchema,
  LedgerEntrySchema,
  LedgerListRequestSchema,
  LedgerListResponseSchema,
  LedgerResponseSchema,
  OrderAdjustmentRequestSchema,
  ProblemDetailsSchema,
  RedemptionCaptureRequestSchema,
  RedemptionReservationResponseSchema,
  RedemptionReservationSchema,
  RedemptionReserveRequestSchema,
  RedemptionReverseRequestSchema,
  RewardCandidateSchema,
  RewardEffectSchema
} from "./loyalty.js";
import {
  BalanceSchema,
  IdentityReferenceSchema,
  MemberEnrollRequestSchema,
  MemberEnrollResponseSchema,
  MemberLookupRequestSchema,
  MemberLookupResponseSchema,
  MemberSchema
} from "./member.js";
import { FoodserviceOrderSchema, OrderAdjustmentSchema, OrderLineSchema, OrderTotalsSchema } from "./order.js";
import { MoneySchema, ProgramScopeSchema, RequestContextSchema, ResponseContextSchema } from "./primitives.js";

export const schemaRegistry = {
  AccountMetric: AccountMetricSchema,
  AccrualPostRequest: AccrualPostRequestSchema,
  Balance: BalanceSchema,
  CatalogRewardDefinition: CatalogRewardDefinitionSchema,
  CapabilitiesDocument: CapabilitiesDocumentSchema,
  EvaluationRequest: EvaluationRequestSchema,
  EvaluationResponse: EvaluationResponseSchema,
  EarningExclusions: EarningExclusionsSchema,
  EarningPolicy: EarningPolicySchema,
  ExpiringBalance: ExpiringBalanceSchema,
  FoodserviceOrder: FoodserviceOrderSchema,
  HealthDocument: HealthDocumentSchema,
  IdentityReference: IdentityReferenceSchema,
  LedgerEntry: LedgerEntrySchema,
  LedgerListRequest: LedgerListRequestSchema,
  LedgerListResponse: LedgerListResponseSchema,
  LedgerResponse: LedgerResponseSchema,
  LoyaltyEvent: LoyaltyEventSchema,
  Member: MemberSchema,
  MemberAccountRequest: MemberAccountRequestSchema,
  MemberAccountResponse: MemberAccountResponseSchema,
  MemberEnrollRequest: MemberEnrollRequestSchema,
  MemberEnrollResponse: MemberEnrollResponseSchema,
  MemberLookupRequest: MemberLookupRequestSchema,
  MemberLookupResponse: MemberLookupResponseSchema,
  Money: MoneySchema,
  OrderAdjustment: OrderAdjustmentSchema,
  OrderAdjustmentRequest: OrderAdjustmentRequestSchema,
  OrderLine: OrderLineSchema,
  OrderTotals: OrderTotalsSchema,
  ProblemDetails: ProblemDetailsSchema,
  PointExpirationPolicy: PointExpirationPolicySchema,
  ProgramAccountDefinition: ProgramAccountDefinitionSchema,
  ProgramCatalog: ProgramCatalogSchema,
  ProgramGetRequest: ProgramGetRequestSchema,
  ProgramGetResponse: ProgramGetResponseSchema,
  ProgramMetricDefinition: ProgramMetricDefinitionSchema,
  ProgramScope: ProgramScopeSchema,
  RedemptionCaptureRequest: RedemptionCaptureRequestSchema,
  RedemptionReservation: RedemptionReservationSchema,
  RedemptionReservationResponse: RedemptionReservationResponseSchema,
  RedemptionReserveRequest: RedemptionReserveRequestSchema,
  RedemptionReverseRequest: RedemptionReverseRequestSchema,
  RequestContext: RequestContextSchema,
  ResponseContext: ResponseContextSchema,
  RewardCandidate: RewardCandidateSchema,
  RewardEffect: RewardEffectSchema,
  TierBenefit: TierBenefitSchema,
  TierDefinition: TierDefinitionSchema,
  TierQualificationPolicy: TierQualificationPolicySchema,
  TierProgress: TierProgressSchema,
  WellKnownDocument: WellKnownDocumentSchema
} satisfies Record<string, TSchema>;
